export const UPDATE_DAYS = "UPDATE_DAYS";
export const UPDATE_HOURS = "UPDATE_HOURS";
export const UPDATE_MINUTES = "UPDATE_MINUTES";
export const UPDATE_SECONDS= "UPDATE_SECONDS";

export const SET_ACTIVE_SESSION = "SET_ACTIVE_SESSION";
